import React, { useCallback, useEffect, useState } from "react";
import { api } from "./api";
import { Badge, Modal } from "./components";
import { dateTime, errorText, money } from "./locale";

const empty = (value: unknown, text = "未设置") => value === "" || value === null || value === undefined ? text : String(value);
const Empty: React.FC<{text: string}> = ({text}) => <div className="empty-state">{text}</div>;

const SubscriptionCard: React.FC<{ sub: any }> = ({ sub }) => <div className="subscription-card">
  <div><span className="eyebrow">订阅版本 {sub.plan_version}</span><h3>{sub.plan_name}</h3></div><Badge value={sub.status} domain="subscription"/>
  {[['每日额度',sub.daily_limit_usd],['每周额度',sub.weekly_limit_usd],['每月额度',sub.monthly_limit_usd]].map(([title,value]) => <div className="quota-line" key={String(title)}><span>{title}</span><b>{money(value)}</b></div>)}
  <small>到期：{dateTime(sub.expires_at, "无到期限制")} · 并发上限：{sub.concurrency_limit} · 可创建密钥数：{sub.max_keys}</small>
</div>;

export const MyOverview: React.FC = () => {
  const [subscriptions, setSubscriptions] = useState<any[]>([]), [keys, setKeys] = useState<any[]>([]);
  useEffect(() => { api.get<any>("/api/admin/me/subscriptions").then(r => setSubscriptions(r.data ?? [])).catch(() => {}); api.get<any>("/api/admin/me/keys").then(r => setKeys(r.data ?? [])).catch(() => {}); }, []);
  const active = subscriptions.filter(s => s.status === "active");
  return <div className="portal"><div className="portal-hero"><span>个人控制台</span><h1>使用订阅，创建接口密钥</h1><p>每个接口密钥都绑定一份订阅；额度和可用账号会随订阅状态实时生效。</p></div><div className="metric-grid"><div className="metric"><b>{active.length}</b><span>可用订阅</span></div><div className="metric"><b>{keys.filter(k => k.status === "active").length}</b><span>已启用接口密钥</span></div><div className="metric"><b>{subscriptions.filter(s => s.status === "expired").length}</b><span>已到期订阅</span></div></div><section className="section-card"><div className="section-title"><h2>可用订阅</h2><a className="btn small" href="#/my-subscriptions">查看全部</a></div>{active.length ? <div className="subscription-cards">{active.map(s => <SubscriptionCard key={s.id} sub={s}/>)}</div> : <Empty text="还没有可用订阅。请联系管理员分配套餐。"/>}</section></div>;
};

export const MySubscriptions: React.FC = () => {
  const [rows, setRows] = useState<any[]>([]), [error, setError] = useState("");
  const load = useCallback(() => api.get<any>("/api/admin/me/subscriptions").then(r => setRows(r.data ?? [])).catch(e => setError(errorText(e))), []);
  useEffect(() => { load(); }, [load]);
  return <div className="portal"><div className="page-head"><h2>我的订阅</h2><div className="grow"/><button className="btn" onClick={load}>刷新</button></div>{error && <div className="error">{error}</div>}<div className="subscription-cards">{rows.length ? rows.map(s => <SubscriptionCard key={s.id} sub={s}/>) : <Empty text="暂时没有套餐订阅。"/>}</div></div>;
};

export const MyKeys: React.FC = () => {
  const [keys, setKeys] = useState<any[]>([]), [subs, setSubs] = useState<any[]>([]), [error, setError] = useState(""), [flash, setFlash] = useState(""), [show, setShow] = useState(false);
  const [form, setForm] = useState({subscription_id:"",name:"",concurrency_limit:"1",expires_at:"",allowed_models:""});
  const load = useCallback(async () => { try { const [keyResult, subResult] = await Promise.all([api.get<any>("/api/admin/me/keys"),api.get<any>("/api/admin/me/subscriptions")]); setKeys(keyResult.data ?? []); setSubs((subResult.data ?? []).filter((s: any) => s.status === "active")); } catch (e) { setError(errorText(e)); } }, []);
  useEffect(() => { load(); }, [load]);
  const create = async () => { try { const result = await api.post<any>("/api/admin/me/keys", {...form, concurrency_limit:Number(form.concurrency_limit), expires_at:form.expires_at ? new Date(form.expires_at).toISOString() : undefined, allowed_models:form.allowed_models.split(",").map(value => value.trim()).filter(Boolean)}); setShow(false); setFlash(`接口密钥已创建，请立即保存：${result.key}`); load(); } catch (e) { setError(errorText(e)); } };
  const update = async (key: any, status: string) => { try { await api.patch(`/api/admin/me/keys/${key.id}`, {status,version:key.version}); load(); } catch (e) { setError(errorText(e)); } };
  const revoke = async (key: any) => { if (!confirm(`撤销接口密钥“${key.name}”后无法恢复，确认继续吗？`)) return; try { await api.post(`/api/admin/me/keys/${key.id}/revoke`); load(); } catch (e) { setError(errorText(e)); } };
  return <div className="portal"><div className="page-head"><h2>我的接口密钥</h2><div className="grow"/><button className="btn primary" disabled={!subs.length} onClick={() => { setForm({subscription_id:subs[0]?.id ?? "",name:"",concurrency_limit:"1",expires_at:"",allowed_models:""}); setShow(true); }}>创建接口密钥</button><button className="btn" onClick={load}>刷新</button></div>{!subs.length && <div className="error">没有可用于创建接口密钥的有效订阅。</div>}{flash && <div className="flash" onClick={() => setFlash("")}>{flash}</div>}{error && <div className="error">{error}</div>}<table className="tbl"><thead><tr><th>名称</th><th>所属套餐</th><th>前缀</th><th>状态</th><th>并发上限</th><th>到期时间</th><th/></tr></thead><tbody>{keys.map(key => <tr key={key.id}><td>{key.name}</td><td>{key.plan_name}</td><td><code>{key.public_prefix}</code></td><td><Badge value={key.status}/></td><td>{key.concurrency_limit}</td><td>{dateTime(key.expires_at,"无到期限制")}</td><td className="actions">{key.status !== "revoked" && <><button className="btn small" onClick={() => update(key,key.status === "active" ? "paused" : "active")}>{key.status === "active" ? "暂停" : "恢复"}</button><button className="btn small danger" onClick={() => revoke(key)}>撤销</button></>}</td></tr>)}</tbody></table>{show && <Modal title="创建接口密钥" onClose={() => setShow(false)} onSubmit={create}><label className="field"><span className="field-label">使用的套餐订阅</span><select value={form.subscription_id} onChange={e => setForm({...form,subscription_id:e.target.value})}>{subs.map(sub => <option key={sub.id} value={sub.id}>{sub.plan_name} · 到期 {dateTime(sub.expires_at,"无到期限制")}</option>)}</select></label><label className="field"><span className="field-label">接口密钥名称</span><input value={form.name} onChange={e => setForm({...form,name:e.target.value})} required/></label><label className="field"><span className="field-label">并发上限</span><input type="number" min="1" value={form.concurrency_limit} onChange={e => setForm({...form,concurrency_limit:e.target.value})}/></label><label className="field"><span className="field-label">到期时间（可选）</span><input type="datetime-local" value={form.expires_at} onChange={e => setForm({...form,expires_at:e.target.value})}/></label><label className="field"><span className="field-label">允许模型（可选，使用逗号分隔）</span><input value={form.allowed_models} onChange={e => setForm({...form,allowed_models:e.target.value})}/></label></Modal>}</div>;
};

export const SecurityPage: React.FC = () => {
  const [oldPassword,setOldPassword] = useState(""), [password,setPassword] = useState(""), [message,setMessage] = useState(""), [error,setError] = useState("");
  const submit = async () => { try { await api.patch("/api/admin/me/password",{old_password:oldPassword,new_password:password}); setMessage("密码已更新，其他登录会话已退出。"); setOldPassword(""); setPassword(""); } catch (e) { setError(errorText(e)); } };
  return <div className="portal narrow"><h2>修改密码</h2><p className="muted">修改成功后，当前会话会保留，其他设备上的登录会话会退出。</p>{message && <div className="flash">{message}</div>}{error && <div className="error">{error}</div>}<label className="field"><span className="field-label">当前密码</span><input type="password" value={oldPassword} onChange={e => setOldPassword(e.target.value)}/></label><label className="field"><span className="field-label">新密码</span><input type="password" value={password} onChange={e => setPassword(e.target.value)}/></label><button className="btn primary" onClick={submit}>更新密码</button></div>;
};

export const AdminPlans: React.FC = () => {
  const [plans,setPlans] = useState<any[]>([]), [pools,setPools] = useState<any[]>([]), [error,setError] = useState(""), [show,setShow] = useState(false); const [form,setForm] = useState<any>({name:"",description:"",daily_limit_usd:"",weekly_limit_usd:"",monthly_limit_usd:"",concurrency_limit:"1",max_keys:"1",default_validity_days:"30",allowed_models:"",pool_ids:[]});
  const load = useCallback(async () => { try { const [planResult,poolResult] = await Promise.all([api.get<any>("/api/admin/plans"),api.get<any>("/api/admin/account-pools")]); setPlans(planResult.data ?? []); setPools(poolResult.data ?? []); } catch (e) { setError(errorText(e)); } }, []); useEffect(() => { load(); },[load]);
  const create = async () => { try { await api.post("/api/admin/plans",{...form,concurrency_limit:Number(form.concurrency_limit),max_keys:Number(form.max_keys),default_validity_days:Number(form.default_validity_days),allowed_models:form.allowed_models.split(",").map((v:string) => v.trim()).filter(Boolean)}); setShow(false); load(); } catch (e) { setError(errorText(e)); } };
  const publish = async (id:string) => { try { await api.post(`/api/admin/plans/${id}/publish`); load(); } catch (e) { setError(errorText(e)); } };
  const reset = () => { setForm({name:"",description:"",daily_limit_usd:"",weekly_limit_usd:"",monthly_limit_usd:"",concurrency_limit:"1",max_keys:"1",default_validity_days:"30",allowed_models:"",pool_ids:[]}); setShow(true); };
  return <div className="portal"><div className="page-head"><h2>套餐管理</h2><div className="grow"/><button className="btn primary" onClick={reset}>创建套餐草稿</button><button className="btn" onClick={load}>刷新</button></div>{error && <div className="error">{error}</div>}<table className="tbl"><thead><tr><th>套餐</th><th>状态</th><th>额度（每日／每周／每月）</th><th>并发／接口密钥数</th><th>账号池</th><th/></tr></thead><tbody>{plans.map(plan => <tr key={plan.id}><td><b>{plan.name}</b><br/><small className="muted">版本 {plan.plan_version} · {plan.description}</small></td><td><Badge value={plan.status} domain="plan"/></td><td>{money(plan.daily_limit_usd)}／{money(plan.weekly_limit_usd)}／{money(plan.monthly_limit_usd)}</td><td>{plan.concurrency_limit}／{plan.max_keys}</td><td>{(plan.pools ?? []).map((pool:any) => pool.name).join("、") || "未配置"}</td><td className="actions">{plan.status === "draft" && <button className="btn small primary" onClick={() => publish(plan.id)}>发布</button>}</td></tr>)}</tbody></table>{show && <Modal title="创建套餐草稿" onClose={() => setShow(false)} onSubmit={create}><label className="field"><span className="field-label">套餐名称</span><input value={form.name} onChange={e => setForm({...form,name:e.target.value})} required/></label><label className="field"><span className="field-label">说明</span><textarea value={form.description} onChange={e => setForm({...form,description:e.target.value})}/></label><div className="form-grid">{[["daily_limit_usd","每日额度（美元）"],["weekly_limit_usd","每周额度（美元）"],["monthly_limit_usd","每月额度（美元）"]].map(([key,title]) => <label className="field" key={key}><span className="field-label">{title}</span><input value={form[key]} placeholder="留空表示不限" onChange={e => setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="form-grid"><label className="field"><span className="field-label">并发上限</span><input type="number" value={form.concurrency_limit} onChange={e => setForm({...form,concurrency_limit:e.target.value})}/></label><label className="field"><span className="field-label">可创建接口密钥数</span><input type="number" value={form.max_keys} onChange={e => setForm({...form,max_keys:e.target.value})}/></label></div><label className="field"><span className="field-label">允许模型（使用逗号分隔，留空表示全部）</span><input value={form.allowed_models} onChange={e => setForm({...form,allowed_models:e.target.value})}/></label><span className="field-label">绑定账号池</span><div className="check-list">{pools.map(pool => <label key={pool.id}><input type="checkbox" checked={form.pool_ids.includes(pool.id)} onChange={e => setForm({...form,pool_ids:e.target.checked ? [...form.pool_ids,pool.id] : form.pool_ids.filter((id:string) => id !== pool.id)})}/>{pool.name}</label>)}</div></Modal>}</div>;
};

export const AdminSubscriptions: React.FC = () => {
  const [rows,setRows] = useState<any[]>([]), [users,setUsers] = useState<any[]>([]), [plans,setPlans] = useState<any[]>([]), [error,setError] = useState(""), [show,setShow] = useState(false); const [form,setForm] = useState({member_id:"",plan_id:"",expires_at:"",notes:""});
  const load = useCallback(async () => { try { const [subResult,userResult,planResult] = await Promise.all([api.get<any>("/api/admin/subscriptions"),api.get<any>("/api/admin/users"),api.get<any>("/api/admin/plans")]); setRows(subResult.data ?? []); setUsers(userResult.data ?? []); setPlans((planResult.data ?? []).filter((plan:any) => plan.status === "active")); } catch (e) { setError(errorText(e)); } }, []); useEffect(() => { load(); },[load]);
  const assign = async () => { try { await api.post("/api/admin/subscriptions",{...form,expires_at:form.expires_at ? new Date(form.expires_at).toISOString() : undefined}); setShow(false); load(); } catch (e) { setError(errorText(e)); } };
  return <div className="portal"><div className="page-head"><h2>订阅分配</h2><div className="grow"/><button className="btn primary" onClick={() => { setForm({member_id:users[0]?.id ?? "",plan_id:plans[0]?.id ?? "",expires_at:"",notes:""}); setShow(true); }}>分配套餐</button><button className="btn" onClick={load}>刷新</button></div>{error && <div className="error">{error}</div>}<table className="tbl"><thead><tr><th>用户</th><th>套餐</th><th>状态</th><th>到期时间</th><th>额度（每日／每周／每月）</th></tr></thead><tbody>{rows.map(sub => <tr key={sub.id}><td>{sub.member_name ?? sub.member_id}</td><td>{sub.plan_name} <small className="muted">版本 {sub.plan_version}</small></td><td><Badge value={sub.status} domain="subscription"/></td><td>{dateTime(sub.expires_at,"无到期限制")}</td><td>{money(sub.daily_limit_usd)}／{money(sub.weekly_limit_usd)}／{money(sub.monthly_limit_usd)}</td></tr>)}</tbody></table>{show && <Modal title="分配套餐" onClose={() => setShow(false)} onSubmit={assign}><label className="field"><span className="field-label">用户</span><select value={form.member_id} onChange={e => setForm({...form,member_id:e.target.value})}>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="field"><span className="field-label">套餐</span><select value={form.plan_id} onChange={e => setForm({...form,plan_id:e.target.value})}>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label className="field"><span className="field-label">到期时间（留空时使用套餐默认有效期）</span><input type="datetime-local" value={form.expires_at} onChange={e => setForm({...form,expires_at:e.target.value})}/></label><label className="field"><span className="field-label">备注</span><textarea value={form.notes} onChange={e => setForm({...form,notes:e.target.value})}/></label></Modal>}</div>;
};

export const AdminUserEntitlements: React.FC<{ memberId:string }> = ({ memberId }) => {
  const [member,setMember] = useState<any>(), [accounts,setAccounts] = useState<any[]>([]), [pools,setPools] = useState<any[]>([]), [accountGrants,setAccountGrants] = useState<any[]>([]), [poolGrants,setPoolGrants] = useState<any[]>([]), [kind,setKind] = useState<"account"|"pool">("account"), [targetID,setTargetID] = useState(""), [priority,setPriority] = useState("50"), [notes,setNotes] = useState(""), [error,setError] = useState("");
  const load = useCallback(async () => { try { const [users,accountResult,poolResult,direct,pooled] = await Promise.all([api.get<any>("/api/admin/users"),api.get<any>("/api/admin/accounts"),api.get<any>("/api/admin/account-pools"),api.get<any>(`/api/admin/users/${memberId}/account-grants`),api.get<any>(`/api/admin/users/${memberId}/pool-grants`)]); setMember((users.data ?? []).find((user:any) => user.id === memberId)); setAccounts((accountResult.data ?? []).filter((account:any) => account.state === "active")); setPools(poolResult.data ?? []); setAccountGrants(direct.data ?? []); setPoolGrants(pooled.data ?? []); } catch (e) { setError(errorText(e)); } },[memberId]); useEffect(() => { load(); },[load]);
  const candidates = kind === "account" ? accounts : pools; useEffect(() => { setTargetID(candidates[0]?.id ?? ""); },[kind,accounts.length,pools.length]);
  const add = async () => { try { await api.post(`/api/admin/users/${memberId}/${kind === "account" ? "account-grants" : "pool-grants"}`,{target_id:targetID,priority:Number(priority),notes}); setNotes(""); load(); } catch (e) { setError(errorText(e)); } };
  const update = async (grant:any, grantKind:"account"|"pool", status:string) => { try { await api.patch(`/api/admin/users/${memberId}/${grantKind === "account" ? "account-grants" : "pool-grants"}/${grant.id}`,{status,version:grant.version}); load(); } catch (e) { setError(errorText(e)); } };
  const Grants: React.FC<{rows:any[]; grantKind:"account"|"pool"; title:string}> = ({rows,grantKind,title}) => <section className="section-card"><div className="section-title"><h2>{title}</h2><span className="muted">仅作为套餐账号池之外的追加资源</span></div>{rows.length ? <table className="tbl"><thead><tr><th>资源</th><th>优先级</th><th>状态</th><th>备注</th><th/></tr></thead><tbody>{rows.map(grant => <tr key={grant.id}><td>{grant.target_name}</td><td>{grant.priority}</td><td><Badge value={grant.status}/></td><td>{empty(grant.notes,"无")}</td><td className="actions">{grant.status !== "revoked" && <button className="btn small danger" onClick={() => update(grant,grantKind,"revoked")}>撤销</button>}{grant.status === "disabled" && <button className="btn small" onClick={() => update(grant,grantKind,"active")}>恢复</button>}</td></tr>)}</tbody></table> : <Empty text="尚未追加资源。"/>}</section>;
  return <div className="portal"><div className="page-head"><h2>{member?.name ?? "用户"} · 资源追加</h2><div className="grow"/><a className="btn" href="#/users">返回用户管理</a><button className="btn" onClick={load}>刷新</button></div><p className="muted">套餐提供基础账号池；这里可以按需给该用户额外绑定单个上游账号或账号池。</p>{error && <div className="error">{error}</div>}<section className="section-card"><h2>追加资源</h2><div className="form-grid"><label className="field"><span className="field-label">资源类型</span><select value={kind} onChange={e => setKind(e.target.value as "account"|"pool")}><option value="account">单个上游账号</option><option value="pool">账号池</option></select></label><label className="field"><span className="field-label">选择资源</span><select value={targetID} onChange={e => setTargetID(e.target.value)}>{candidates.map(item => <option key={item.id} value={item.id}>{item.label ?? item.name}</option>)}</select></label><label className="field"><span className="field-label">优先级</span><input type="number" min="1" value={priority} onChange={e => setPriority(e.target.value)}/></label><label className="field"><span className="field-label">备注</span><input value={notes} onChange={e => setNotes(e.target.value)}/></label></div><button className="btn primary" disabled={!targetID} onClick={add}>追加给此用户</button></section><Grants rows={accountGrants} grantKind="account" title="已分配的单个账号"/><Grants rows={poolGrants} grantKind="pool" title="已分配的账号池"/></div>;
};
